### ISSUE TITLE
[kahi_scholar_person] error con set

### ISSUE THREAD

**Issue by omazapa** [colav/impactu#147]
set no soporta ids con diccionarios, toca buscar una alternaitva para hacer unicidad sobre esos ids.

```
[Parallel(n_jobs=20)]: Using backend ThreadingBackend with 20 concurrent workers.
Plugin scholar_person failed
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/joblib/_parallel_backends.py", line 273, in _wrap_func_call
    return func()
           ^^^^^^
  File "/usr/lib/python3/dist-packages/joblib/parallel.py", line 589, in __call__
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ozapatam/.local/lib/python3.12/site-packages/kahi_scholar_person/process_one.py", line 22, in process_one
    db_author_set = set(tuple(d.items()) for d in author_db["related_works"])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'dict'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ozapatam/.local/bin/kahi_run", line 37, in <module>
    kahi.run()
  File "/home/ozapatam/.local/lib/python3.12/site-packages/kahi/Kahi.py", line 144, in run
    status = run()
             ^^^^^
  File "/home/ozapatam/.local/lib/python3.12/site-packages/kahi_scholar_person/Kahi_scholar_person.py", line 89, in run
    self.process_scholar()
  File "/home/ozapatam/.local/lib/python3.12/site-packages/kahi_scholar_person/Kahi_scholar_person.py", line 71, in process_scholar
    Parallel(
  File "/usr/lib/python3/dist-packages/joblib/parallel.py", line 1952, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/joblib/parallel.py", line 1595, in _get_outputs
    yield from self._retrieve()
  File "/usr/lib/python3/dist-packages/joblib/parallel.py", line 1699, in _retrieve
    self._raise_error_fast()
  File "/usr/lib/python3/dist-packages/joblib/parallel.py", line 1734, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/usr/lib/python3/dist-packages/joblib/parallel.py", line 736, in get_result
    return self._return_or_raise()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/joblib/parallel.py", line 754, in _return_or_raise
    raise self._result
TypeError: unhashable type: 'dict'
ozapatam@tuxito:/storage/kahi_data
```

**Comment by omazapa** [comment]
fixed via https://github.com/omazapa/Kahi_plugins/commit/21896766da919b09ed24173509b837e52736b878
