### ISSUE TITLE
Index Error split_name

### ISSUE THREAD

**Issue by omazapa** [colav/impactu#155]
algunos nombres están produciendo 
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/joblib/_parallel_backends.py", line 273, in _wrap_func_call
    return func()
           ^^^^^^
  File "/usr/lib/python3/dist-packages/joblib/parallel.py", line 589, in __call__
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ozapatam/.local/lib/python3.12/site-packages/kahi_authors_unicity/Kahi_authors_unicity.py", line 273, in doi_unicity
    author_match = compare_author(author, other_author)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ozapatam/.local/lib/python3.12/site-packages/kahi_impactu_utils/Utils.py", line 684, in compare_author
    author2_names = split_names(author2["full_name"])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ozapatam/.local/lib/python3.12/site-packages/kahi_impactu_utils/Utils.py", line 164, in split_names
    d['initials'] = "".join([x[0] for x in d['first_names']])
                             ~^^^
IndexError: string index out of range
```
estos son algunos de los que producen el traceback y paran la ejecución:
```

{'_id': ObjectId('65cc0373dd7fa9d496354f8b'), 'display_name': '-Jaimes Yelson Alejandro Picon'}
{'_id': ObjectId('665acc8933eafe395492d5ec'), 'display_name': '-Nc-Nd Revista'}
{'_id': ObjectId('665aaf85d50f52e33bff44f7'), 'display_name': '- Comité de acreditación'}
{'_id': ObjectId('665ac3ef7c38b898f7d0a581'), 'display_name': '- Le D'}
{'_id': ObjectId('665ab7e40c995c2148c8efb1'), 'display_name': '- Wan-Ok Lee'}

```

see le quitará el acaractaer a los nombres que lo contengan al inicio

```
name = '-Jaimes Yelson Alejandro Picon'
if name.startswith('-'):
    name = name[1:].strip()
split_names(name)

{'first_names': ['Jaimes', 'Yelson'],
 'last_names': ['Alejandro', 'Picon'],
 'full_name': 'Jaimes Yelson Alejandro Picon',
 'initials': 'JY'}
```

**Comment by omazapa** [comment]
fixed via https://github.com/omazapa/Kahi_impactu_utils/commit/9d78745a483975846349efe6b059acf8bedd17d1
