### ISSUE TITLE
[kahi_minciencias_opendata_works] key error initials 

### ISSUE THREAD

**Issue by omazapa** [colav/impactu#156]
Plugin minciencias_opendata_works failed
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/joblib/_parallel_backends.py", line 273, in _wrap_func_call
    return func()
           ^^^^^^
  File "/usr/lib/python3/dist-packages/joblib/parallel.py", line 589, in __call__
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ozapatam/.local/lib/python3.12/site-packages/kahi_minciencias_opendata_works/process_one.py", line 361, in process_one
    process_one_update(
  File "/home/ozapatam/.local/lib/python3.12/site-packages/kahi_minciencias_opendata_works/process_one.py", line 115, in process_one_update
    name_match = compare_author(
                 ^^^^^^^^^^^^^^^
  File "/home/ozapatam/.local/lib/python3.12/site-packages/kahi_impactu_utils/Utils.py", line 682, in compare_author
    if compare_authors_initials(author1["initials"], author1["last_names"][0], author2["initials"], author2["last_names"][0]):
                                ~~~~~~~^^^^^^^^^^^^
KeyError: 'initials'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ozapatam/.local/bin/kahi_run", line 37, in <module>
    kahi.run()
  File "/home/ozapatam/.local/lib/python3.12/site-packages/kahi/Kahi.py", line 144, in run
    status = run()
             ^^^^^
  File "/home/ozapatam/.local/lib/python3.12/site-packages/kahi_minciencias_opendata_works/Kahi_minciencias_opendata_works.py", line 141, in run
    self.process_opendata()
  File "/home/ozapatam/.local/lib/python3.12/site-packages/kahi_minciencias_opendata_works/Kahi_minciencias_opendata_works.py", line 123, in process_opendata
    Parallel(
  File "/usr/lib/python3/dist-packages/joblib/parallel.py", line 1952, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/joblib/parallel.py", line 1595, in _get_outputs
    yield from self._retrieve()
  File "/usr/lib/python3/dist-packages/joblib/parallel.py", line 1699, in _retrieve
    self._raise_error_fast()
  File "/usr/lib/python3/dist-packages/joblib/parallel.py", line 1734, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/usr/lib/python3/dist-packages/joblib/parallel.py", line 736, in get_result
    return self._return_or_raise()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/joblib/parallel.py", line 754, in _return_or_raise
    raise self._result
KeyError: 'initials'

**Comment by omazapa** [comment]
fixed via https://github.com/omazapa/Kahi_plugins/commit/724509e9067b2daad1f5d5843a3cbfd4355a1af1

required, because we are implementing optimize queries
