### ISSUE TITLE
Error elastic Search

### ISSUE THREAD

**Issue by omazapa** [colav/impactu#199]
Para solucionar este problema se tiene que hacer los siguente:

- [x] implementar .close en [mohan](https://github.com/colav/mohan)
- [x] Añadir opciones tales como retry_on_timeout, max_retries en  [mohan](https://github.com/colav/mohan)
- [x] Añadir search.default_search_timeout  en [Chia](https://github.com/colav/Chia)
- [x] Implementar ES_JAVA_OPTS con almenos 8M y ponerlo como opcion en .env en [Chia](https://github.com/colav/Chia)
- [x] añadir soporte para elegir el tipo de backend en **[kahi_openalex_works]**, para por ejemplo pasar "threading"
- [x] separar bien el código de multiprocessing y threading para **[kahi_openalex_works]**, implementar bien la instacia de Mongo t Similarity junto con su respectivo close.
- [x] pasar el objeto client de mongo y similarity a process_one en **[kahi_openalex_works]** si es threading 

```
WARNING:elastic_transport.node_pool:Node <Urllib3HttpNode(http://localhost:9200)> has failed for 1 times in a row, putting on 1 second timeout
WARNING:elastic_transport.transport:Retrying request after failure (attempt 0 of 3)
Traceback (most recent call last):
  File "/home/ozapatam/.local/lib/python3.12/site-packages/elastic_transport/_transport.py", line 342, in perform_request
  File "/home/ozapatam/.local/lib/python3.12/site-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
elastic_transport.ConnectionError: Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x73781ad51e20>: Failed to establish a new connection: [Errno 16] Device or resource busy)
WARNING:elastic_transport.node_pool:Node <Urllib3HttpNode(http://localhost:9200)> has failed for 2 times in a row, putting on 2 second timeout
WARNING:elastic_transport.transport:Retrying request after failure (attempt 1 of 3)
Traceback (most recent call last):
  File "/home/ozapatam/.local/lib/python3.12/site-packages/elastic_transport/_transport.py", line 342, in perform_request
  File "/home/ozapatam/.local/lib/python3.12/site-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
elastic_transport.ConnectionError: Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x73781ad52090>: Failed to establish a new connection: [Errno 16] Device or resource busy)
WARNING:elastic_transport.node_pool:Node <Urllib3HttpNode(http://localhost:9200)> has failed for 3 times in a row, putting on 4 second timeout
WARNING:elastic_transport.transport:Retrying request after failure (attempt 2 of 3)
Traceback (most recent call last):
  File "/home/ozapatam/.local/lib/python3.12/site-packages/elastic_transport/_transport.py", line 342, in perform_request
  File "/home/ozapatam/.local/lib/python3.12/site-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x73781ad52360>: Failed to establish a new connection: [Errno 16] Device or resource busy)
WARNING:elastic_transport.node_pool:Node <Urllib3HttpNode(http://localhost:9200)> has been marked alive after a successful request
WARNING:elastic_transport.node_pool:Node <Urllib3HttpNode(http://localhost:9200)> has failed for 1 times in a row, putting on 1 second timeout
WARNING:elastic_transport.transport:Retrying request after failure (attempt 0 of 3)
Traceback (most recent call last):
  File "/home/ozapatam/.local/lib/python3.12/site-packages/elastic_transport/_transport.py", line 342, in perform_request
  File "/home/ozapatam/.local/lib/python3.12/site-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x73781adf06e0>: Failed to establish a new connection: [Errno 16] Device or resource busy)
WARNING:elastic_transport.node_pool:Node <Urllib3HttpNode(http://localhost:9200)> has failed for 2 times in a row, putting on 2 second timeout
WARNING:elastic_transport.transport:Retrying request after failure (attempt 1 of 3)
Traceback (most recent call last):
  File "/home/ozapatam/.local/lib/python3.12/site-packages/elastic_transport/_transport.py", line 342, in perform_request
  File "/home/ozapatam/.local/lib/python3.12/site-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x73781adf1f10>: Failed to establish a new connection: [Errno 16] Device or resource busy)
WARNING:elastic_transport.node_pool:Node <Urllib3HttpNode(http://localhost:9200)> has failed for 3 times in a row, putting on 4 second timeout
WARNING:elastic_transport.transport:Retrying request after failure (attempt 2 of 3)
Traceback (most recent call last):
  File "/home/ozapatam/.local/lib/python3.12/site-packages/elastic_transport/_transport.py", line 342, in perform_request
  File "/home/ozapatam/.local/lib/python3.12/site-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x73781adf39e0>: Failed to establish a new connection: [Errno 16] Device or resource busy)
WARNING:elastic_transport.node_pool:Node <Urllib3HttpNode(http://localhost:9200)> has failed for 4 times in a row, putting on 8 second timeout
Exception in thread Thread-3 (_handle_results):
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.12/threading.py", line 1010, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.12/multiprocessing/pool.py", line 579, in _handle_results
    task = get()
           ^^^^^
  File "/usr/lib/python3.12/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: NewConnectionError.__init__() missing 1 required positional argument: 'message'
WARNING:elastic_transport.node_pool:Node <Urllib3HttpNode(http://localhost:9200)> has failed for 1 times in a row, putting on 1 second timeout
WARNING:elastic_transport.transport:Retrying request after failure (attempt 0 of 3)
Traceback (most recent call last):
  File "/home/ozapatam/.local/lib/python3.12/site-packages/elastic_transport/_transport.py", line 342, in perform_request
  File "/home/ozapatam/.local/lib/python3.12/site-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x73781ade5df0>: Failed to establish a new connection: [Errno 16] Device or resource busy)
WARNING:elastic_transport.node_pool:Node <Urllib3HttpNode(http://localhost:9200)> has failed for 2 times in a row, putting on 2 second timeout
WARNING:elastic_transport.transport:Retrying request after failure (attempt 1 of 3)
Traceback (most recent call last):
  File "/home/ozapatam/.local/lib/python3.12/site-packages/elastic_transport/_transport.py", line 342, in perform_request
  File "/home/ozapatam/.local/lib/python3.12/site-packages/elastic_transport/_node/_http_urllib3.py", line 202, in perform_request
    raise err from None
elastic_transport.ConnectionError: Connection error caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x73781ade5910>: Failed to establish a new connection: [Errno 16] Device or resource busy)
WARNING:elastic_transport.node_pool:Node <Urllib3HttpNode(http://localhost:9200)> has been marked alive after a successful request
``

**Comment by omazapa** [comment]
el pronlema no es el docker del paquete Chia, el problema es joblib multiprocessing.

```
https://elasticsearch-py.readthedocs.io/en/v7.13.2/

Since we use persistent connections throughout the client it means that the client doesn’t tolerate fork very well. If your application calls for multiple processes make sure you create a fresh client after call to fork. Note that Python’s multiprocessing module uses fork to create new processes on POSIX systems.
```
