### ISSUE TITLE
scienti Error en ejecución del ETL

### ISSUE THREAD

**Issue by omazapa** [colav/impactu#365]
```
Plugin scienti_works failed
joblib.externals.loky.process_executor._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/dist-packages/joblib/_utils.py", line 72, in __call__
    return self.func(**kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/joblib/parallel.py", line 598, in __call__
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ozapatam/.local/lib/python3.12/site-packages/kahi_scienti_works/process_one.py", line 708, in process_one
    process_one_update(scienti_reg, colav_reg, db,
  File "/home/ozapatam/.local/lib/python3.12/site-packages/kahi_scienti_works/process_one.py", line 297, in process_one_update
    process_author(entry, colav_reg, db, verbose)
  File "/home/ozapatam/.local/lib/python3.12/site-packages/kahi_scienti_works/process_one.py", line 161, in process_author
    author_affiliations = [str(aff['id'])
                               ~~~^^^^^^
KeyError: 'id'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ozapatam/.local/bin/kahi_run", line 37, in <module>
    kahi.run()
  File "/home/ozapatam/.local/lib/python3.12/site-packages/kahi/Kahi.py", line 151, in run
    status = run()
             ^^^^^
  File "/home/ozapatam/.local/lib/python3.12/site-packages/kahi_scienti_works/Kahi_scienti_works.py", line 269, in run
    self.process_scienti(self.db, self.collection, config)
  File "/home/ozapatam/.local/lib/python3.12/site-packages/kahi_scienti_works/Kahi_scienti_works.py", line 225, in process_scienti
    Parallel(
  File "/usr/local/lib/python3.12/dist-packages/joblib/parallel.py", line 2007, in __call__
    return output if self.return_generator else list(output)
                                                ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/joblib/parallel.py", line 1650, in _get_outputs
    yield from self._retrieve()
  File "/usr/local/lib/python3.12/dist-packages/joblib/parallel.py", line 1754, in _retrieve
    self._raise_error_fast()
  File "/usr/local/lib/python3.12/dist-packages/joblib/parallel.py", line 1789, in _raise_error_fast
    error_job.get_result(self.timeout)
  File "/usr/local/lib/python3.12/dist-packages/joblib/parallel.py", line 745, in get_result
    return self._return_or_raise()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/joblib/parallel.py", line 763, in _return_or_raise
    raise self._result
KeyError: 'id'
Register with COD_RH: 0000086320 and COD_PRODUCTO: 30443 could not be linked to a source (no ids and no name)
````

**Comment by omazapa** [comment]
En este registro la afiliación universidad de antiqouia no tiene id
```
{'affiliations': [{'name': 'Universidad de Antioquia',
                   'types': [{'source': 'ror', 'type': 'Education'},
                             {'source': 'openalex', 'type': 'education'}]},
                  {'id': '03bp5hc83_25',
                   'name': 'Facultad de Ingeniería',
                   'types': [{'source': 'staff', 'type': 'faculty'}]},
                  {'id': '03bp5hc83_25_21320004_3412',
                   'name': 'Departamento de Ingeniería Metalúrgica',
                   'types': [{'source': 'staff', 'type': 'department'}]}],
 'full_name': 'Jorge Andres Calderon Gutierrez',
 'id': ObjectId('675117f5ec597380e35b395c')}
```

eso pasa para el paper 
```
[{'title': 'Performance improvement of macroporous polypyrrole sensor for detection of ammonia by incorporation of magnetite nanoparticles',
  'lang': 'en',
  'source': 'openalex'},
 {'title': 'Performance improvement of macroporous polypyrrole sensor fordetection of ammonia by incorporation of magnetite nanoparticles',
  'lang': 'en',
  'source': 'scienti'},
 {'title': 'PERFORMANCE IMPROVEMENT OF MACROPOROUS POLYPYRROLE SENSOR FOR DETECTION OF AMMONIA BY INCORPORATION OF MAGNETITE NANOPARTICLES',
  'lang': 'en',
  'source': 'ciarp',
  'provenance': 'ciarp'},
 {'title': 'Performance improvement of macroporous polypyrrole sensor for detection of ammonia by incorporation of magnetite nanoparticles',
  'lang': 'en',
  'source': 'scholar'}]
```

**Comment by omazapa** [comment]
@fedevergara 
al parecer el error viene de https://github.com/colav/Kahi_plugins/pull/343

lo que está pasando es que dentro del work en al afilación del author para la institución no hay  id

ejemplo:

```
{'id': ObjectId('675117f5ec597380e35b395c'),
 'full_name': 'Jorge Andres Calderon Gutierrez',
 'affiliations': [{'name': 'Universidad de Antioquia',
   'types': [{'source': 'ror', 'type': 'Education'},
    {'source': 'openalex', 'type': 'education'}]},
  {'id': '03bp5hc83_25',
   'name': 'Facultad de Ingeniería',
   'types': [{'source': 'staff', 'type': 'faculty'}]},
  {'id': '03bp5hc83_25_21320004_3412',
   'name': 'Departamento de Ingeniería Metalúrgica',
   'types': [{'source': 'staff', 'type': 'department'}]}]}
```
tenemos que verificar que la insitucion para el author en los trabajos de CIARP si tenga el id
